environment:
  matrix:
    - PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      MINICONDA: "C:\\Miniconda"

    - PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      MINICONDA: "C:\\Miniconda-x64"

    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      MINICONDA: "C:\\Miniconda3"

    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      MINICONDA: "C:\\Miniconda3-x64"

init:
  - "ECHO %PYTHON_VERSION% %PYTHON_ARCH% %MINICONDA%"

install:
  - ps: .\.appveyor_update_version.ps1
  - "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% cython numpy scipy"
  - activate test-environment

build_script:
  - pip install -e .

test_script:
  - python -m unittest discover bandmat
