language: python

python:
  - "2.7"
  - "3.4"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install cython python-numpy python-scipy
  - sudo apt-get -qq install cython3 python3-numpy python3-scipy

install:
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace

script:
  - python -m unittest discover bandmat
